### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by hbi99** [Scandit/barcodescanner-sdk-cordova#61]
The installation is to complex and despite the fact that I am following the instructions, it does not work :-(

In the simple example, nothing happens when clicking the "Scan" button.
After troubleshooting, I've noticed that `cordova.plugins.barcodeScanner` is available but `window.Scandit` is **undefined**. I have tried using Scandit a few years ago but didn't got it working then. Now, I was hoping that you would've managed to simplify - no luck :-(

I am using PhoneGap, iOS and MacOS.

**Comment by moritz-scandit** [comment]
Hi Hakan,

We're sorry to hear that you are having problems adding our plugin to your project. We are not aware of it being very complex as all you should need to do is call "phonegap plugin add" and that's it. If window.Scandit is undefined then the adding of the plugin somehow failed and you should see a message that tells you what went wrong. Please also be aware that you have to build and deploy the app yourself for our plugin to work as it makes use of native components, you are not able to use the Phonegap Desktop App to deploy an app with our plugin.

We would gladly try to identify your issue but need more information to do so. For example the output when you call "phonegap plugin add" for our plugin and optimally the actual project where you tried adding it, as it is very difficult to understand what is going wrong otherwise.

**Comment by swenner** [comment]
Please try to reproduce this issue with the latest version of the SDK (5.3.0BETA2) and reopen the ticket if necessary. Thank you.
